### ISSUE TITLE
linux 下如何使用呢？

### ISSUE THREAD

**Issue by hhls** [tonydon140/dns-test-tool#1]

**Comment by tonydon140** [comment]
目前还没有打包至Linux平台，您可以使用Python直接运行main.py：
```
pip install PySide6, requests, ping3

python python/main.py
```

**Comment by hhls** [comment]
> 目前还没有打包至Linux平台，您可以使用Python直接运行main.py：
> 
> ```
> pip install PySide6, requests, ping3
> 
> python python/main.py
> ```

感谢支持https://tonydon.top:6515/admin/dns/list 访问不通

**Comment by tonydon140** [comment]
> > 目前还没有打包至Linux平台，您可以使用Python直接运行main.py：
> > ```
> > pip install PySide6, requests, ping3
> > 
> > python python/main.py
> > ```
> 
> 感谢支持https://tonydon.top:6515/admin/dns/list 访问不通

现在应该是可以正常访问的。

**Comment by tonydon140** [comment]
现在v1.0.0版本支持多平台使用
