### ISSUE TITLE
关于结果排序问题

### ISSUE THREAD

**Issue by 9aiYuki** [tonydon140/dns-test-tool#2]
目前我在mac端直接运行python的main文件，最终得出结果后点击延时排序是按照字符型排序的，也就是说100延迟会排在11延迟的前面，建议按照数字型来排序，然后将timeout放在最后。如下图：
![image](https://github.com/tonydon140/dns-test-tool/assets/39363768/f3142b4d-2ba5-4311-8dc0-8f8d01cc59e2)

**Comment by tonydon140** [comment]
感谢您的使用和反馈👍，我会在后续的版本尝试修复它😊

**Comment by tonydon140** [comment]
v1.0.0版本已经修复

**Comment by tonydon140** [comment]
修复
